version: "3.9"

services:
  oms-dockview:
    build: .
    container_name: oms-dockview
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules        # Prevent node_modules from being overwritten
      # - ./config/config.js:/public/config.js #by default in public/config.js
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
